name: Build binaries

on:
  workflow_dispatch:
    inputs:
      ui-version:
        description: 'RDMS DEVCON UI Version'
        required: true
        default: '1.0.0'
        type: string
      svc-version:
        description: 'RDMS DEVCON SVC Version'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Build for x64
        run: |
          ./scripts/publish.ps1 -target ToyboxImageConverter/ToyboxImageConverter.csproj -publishprofile x64.pubxml -productName "${{ inputs.product-name }}" -productVersion "${{ inputs.product-version }}" -fileDesc "${{ inputs.file-desc }}" -fileVersion "${{ inputs.file-version }}" -company "${{ inputs.company }}" -copyright "${{ inputs.copyright }}" -excludeSymbols $${{ inputs.remove-debug-symbols }}
        shell: pwsh
        
      - name: Build for ARM64
        run: |
          ./scripts/publish.ps1 -target ToyboxImageConverter/ToyboxImageConverter.csproj -publishprofile arm64.pubxml -productName "${{ inputs.product-name }}" -productVersion "${{ inputs.product-version }}" -fileDesc "${{ inputs.file-desc }}" -fileVersion "${{ inputs.file-version }}" -company "${{ inputs.company }}" -copyright "${{ inputs.copyright }}" -excludeSymbols $${{ inputs.remove-debug-symbols }}
        shell: pwsh
        
      - name: Copy licenses
        run: |
          New-Item -Path "./src/ToyboxImageConverter/bin/publish/x64" -Name "docs" -ItemType "directory"
          New-Item -Path "./src/ToyboxImageConverter/bin/publish/arm64" -Name "docs" -ItemType "directory"
          Copy-Item -Path "./docs/*" -Destination "./src/ToyboxImageConverter/bin/publish/x64/docs"
          Copy-Item -Path "./docs/*" -Destination "./src/ToyboxImageConverter/bin/publish/arm64/docs"
        shell: pwsh
        
      - name: Compress build outputs
        run: |
          Compress-Archive -Path ./src/ToyboxImageConverter/bin/publish/x64/* -DestinationPath ./x64.zip -Force
          Compress-Archive -Path ./src/ToyboxImageConverter/bin/publish/arm64/* -DestinationPath ./arm64.zip -Force
        shell: pwsh
        
      - name: Download VIPS
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "project-toybox/toybox-vips"
          latest: true
          fileName: "*.zip"
          
      - name: Decompress and copy VIPS
        run: |
          New-Item -Path "./" -Name "vips-x64" -ItemType "directory"
          New-Item -Path "./" -Name "vips-arm64" -ItemType "directory"
          Expand-Archive -Path "./vips-dev-w64-all-*-hevc.zip" -DestinationPath "./vips-x64"
          Expand-Archive -Path "./vips-dev-arm64-all-*-hevc.zip" -DestinationPath "./vips-arm64"
          Copy-Item -Path "./vips-x64/vips-dev-*/bin/*" -Destination "./src/ToyboxImageConverter/bin/publish/x64/" -Recurse
          Copy-Item -Path "./vips-arm64/vips-dev-*/bin/*" -Destination "./src/ToyboxImageConverter/bin/publish/arm64/" -Recurse
        shell: pwsh
        
      - name: Compress build outputs with VIPS
        run: |
          Compress-Archive -Path ./src/ToyboxImageConverter/bin/publish/x64/* -DestinationPath ./x64-with-vips.zip -Force
          Compress-Archive -Path ./src/ToyboxImageConverter/bin/publish/arm64/* -DestinationPath ./arm64-with-vips.zip -Force
        shell: pwsh   
        
      - name: Upload build outputs
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: |
            ./x64.zip
            ./arm64.zip
            ./x64-with-vips.zip
            ./arm64-with-vips.zip
            
  
  release:
    needs: build
    name: Release to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build outputs
        uses: actions/download-artifact@v3
        with:
          name: build-outputs
          
      - id: create-release
        name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.file-version }}
          release_name: v${{ inputs.file-version }}
          draft: false
          prerelease: false
          
      - name: Upload the x64 build output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./x64.zip
          asset_name: toybox-image-converter-w64-${{ inputs.file-version }}.zip
          asset_content_type: application/zip
          
      - name: Upload the ARM64 build output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./arm64.zip
          asset_name: toybox-image-converter-arm64-${{ inputs.file-version }}.zip
          asset_content_type: application/zip
          
      - name: Upload the x64(with VIPS) build output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./x64-with-vips.zip
          asset_name: toybox-image-converter-with-vips-w64-${{ inputs.file-version }}.zip
          asset_content_type: application/zip
          
      - name: Upload the ARM64(with VIPS) build output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./arm64-with-vips.zip
          asset_name: toybox-image-converter-with-vips-arm64-${{ inputs.file-version }}.zip
          asset_content_type: application/zip